-- ==========================================================================================================================
-- Magnitude Analysis
-- ==========================================================================================================================
/* Script used:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.
*/

-- Find total customers by country
SELECT country,
       COUNT(customer_key) 'Total Customers'
FROM gold.dim_customers
GROUP BY country
ORDER BY 2 DESC

-- Find total customers by gender
SELECT gender,
       COUNT(customer_key) 'Total Customers'
FROM gold.dim_customers
GROUP BY gender
ORDER BY 2 DESC

-- Find total products by category
SELECT category,
       COUNT(product_key) 'Total Products'
FROM gold.dim_products
GROUP BY category
ORDER BY 2 DESC

-- What is the average costs in each category?
SELECT category,
       AVG(cost) 'Average Costs'
FROM gold.dim_products
GROUP BY category
ORDER BY 2 DESC

-- What is the total revenue generated for each category?
SELECT p.category,
       SUM(f.sales_amount) 'Total Revenue'
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON	  p.product_key = f.product_key
GROUP BY p.category
ORDER BY 2 DESC

-- Find total revenue generated by each customer
SELECT c.customer_key,
       c.first_name,
       c.last_name,
       SUM(f.sales_amount) 'Total Revenue'
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON	  c.customer_key = f.customer_key
GROUP BY c.customer_key,
         c.first_name,
	 c.last_name
ORDER BY 4 DESC

-- What is the distribution of sold items across countries?
SELECT c.country,
       SUM(f.quantity) 'Total Items Sold'
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON	  c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY 2 DESC

